name: build-asy-cxx-linux
on:
  workflow_call:
    inputs:
      version_override:
        type: string
        default: ""
  workflow_dispatch:
    inputs:
      version_override:
        type: string
        description: Version override. If not given, will use the default value in configure.ac.
        default: ""

jobs:
  configure-linux-release-x64:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/initialize-linux-env
      - run: |
          ASY_VERSION_OVERRIDE="${{ inputs.version_override }}" cmake --preset linux/release/ci/with-ccache
      - name: tar+gz cmake configuration
        run: tar -czf cmake-linux-cfg-artifact.tar.gz --exclude='vcpkg_installed' cmake-build-linux/release
      - name: Upload configuration artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cmake-linux-x64-release-cfg-tgz
          path: cmake-linux-cfg-artifact.tar.gz
  build-linux-release-x64:
    needs: configure-linux-release-x64
    runs-on: "ubuntu-22.04"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/initialize-linux-env
      - name: Download configuration artifacts
        uses: actions/download-artifact@v4
        with:
          name: cmake-linux-x64-release-cfg-tgz
      - name: Untar configuration artifact
        run: tar -xzf cmake-linux-cfg-artifact.tar.gz
        # Why we are defining version here and not in configuration stage is because cmake gets
        # re-run here
      - name: Generate version suffix
        if: ${{ inputs.version_override == '' }}
        run: |
          echo set\(ASY_VERSION_SUFFIX \"/github-ci/ref=${{ github.sha }}\"\) > asy-pkg-version-suffix.cmake
      - run: cmake --build --preset linux/release --target asy-with-basefiles -j
      - name: build misc files
        run: cmake --build --preset linux/release/ci/with-ccache --target asy-dist-misc-files -j
      - name: Archive build files
        uses: actions/upload-artifact@v4
        with:
          name: asy-buildfiles
          path: |
            cmake-build-linux/release/asy
            cmake-build-linux/release/base
      - name: Archive misc files
        uses: actions/upload-artifact@v4
        with:
          name: asy-miscfiles
          path: |
            cmake-build-linux/release/misc-output
      - name: Build Asymptote google test files
        run: cmake --build --preset linux/release --target asyCxxTests -j
      - name: Archive Asymptote gtest files
        uses: actions/upload-artifact@v4
        with:
          name: asy-gtest-files
          path: |
            cmake-build-linux/release/cxxtests/asyCxxTests
            cmake-build-linux/release/cxxtests/*.cmake
      - name: Archive Asymptote test files
        uses: actions/upload-artifact@v4
        with:
          name: asy-testfiles
          path: cmake-build-linux/release/CTest*.cmake
  linux-asy-docgen:
    runs-on: "ubuntu-22.04"
    needs: build-linux-release-x64
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/initialize-linux-env
      - uses: ./.github/actions/initialize-linux-latex-and-gs
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-buildfiles
          path: cmake-build-linux/release/
      - name: delete cache file
        run: rm -f cmake-build-linux/release/CMakeCache.txt
      - name: reconfigure with documentation
        run: ASY_VERSION_OVERRIDE="${{ inputs.version_override }}" cmake --preset linux/release/ci/with-ccache
      - name: touch asymptote binary (to avoid need for rebuilding)
        run: touch cmake-build-linux/release/asy
      - name: build documentation
        run: cmake --build --preset linux/release/ci/with-ccache --target docgen -j
      - name: Archive asymptote.pdf
        uses: actions/upload-artifact@v4
        with:
          name: asy-pdf-file
          path: cmake-build-linux/release/docbuild/asymptote.pdf
      - name: Archive remaining asymptote documentation
        uses: actions/upload-artifact@v4
        with:
          name: asy-misc-docs
          path: |
            cmake-build-linux/release/docbuild/asy-latex.pdf
            cmake-build-linux/release/docbuild/asymptote.sty
            cmake-build-linux/release/docbuild/CAD.pdf
            cmake-build-linux/release/docbuild/asyRefCard.pdf
            cmake-build-linux/release/docbuild/TeXShopAndAsymptote.pdf
  package-asymptote-artifacts:
    needs: [linux-asy-docgen]
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: asy-buildfiles
        path: tar-stage
    - name: Download misc files
      uses: actions/download-artifact@v4
      with:
        name: asy-miscfiles
        path: tar-stage/misc/
    - name: Download asymptote.pdf
      uses: actions/download-artifact@v4
      with:
        name: asy-pdf-file
        path: tar-stage/doc/
    - name: Download remaining documentation files
      uses: actions/download-artifact@v4
      with:
        name: asy-misc-docs
        path: tar-stage/doc/
    - name: Link examples directory to tar-stage
      run: ln -sf ${{ github.workspace }}/examples ${{ github.workspace }}/tar-stage/examples
    - name: Set asy's +x flag
      run: chmod +x tar-stage/asy
    - name: tar package
      run: tar -C tar-stage -cvhf asymptote-build-linux.tar asy base examples doc misc
    - name: Archive Asymptote test files
      uses: actions/upload-artifact@v4
      with:
        name: asymptote-build-linux
        path: asymptote-build-linux.tar
