name: test-asy-windows
on:
  workflow_call:

# this is to be run after build-asy-windows is completed
jobs:
  test-windows-msvc-x64-cxxtests:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/initialize-windows-env
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-win-x64-testfiles
          path: cmake-build-msvc/release/
      - name: Download artifacts for gtest
        uses: actions/download-artifact@v4
        with:
          name: asy-win-x64-gtest-files
          path: cmake-build-msvc/release/cxxtests
      - name: google test
        run: ctest --test-dir cmake-build-msvc/release -R "^cxxtests."
  test-windows-msvc-x64-asy-tests:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: ./.github/actions/initialize-windows-env
      - uses: ./.github/actions/initialize-windows-latex-and-gs
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-win-x64-buildfiles
          path: cmake-build-msvc/release/
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: asy-win-x64-testfiles
          path: cmake-build-msvc/release/
      - name: asy test
        run: |
          $env:PATH="C:/texlive/bin/windows/;$env:PATH"
          ctest --output-on-failure --test-dir cmake-build-msvc/release -L "asy-check-tests"
