name: initialize-env
description: Initialize environment
runs:
  using: 'composite'
  steps:
    - name: Install ninja
      shell: pwsh
      run: choco install ninja -y
    - name: Cache Vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\vcpkg\archives
        key: ${{ runner.os }}-vcpkg-cache
    - name: Set environment variables
      shell: pwsh
      run: |
        Write-Output "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
