name: initialize-windows-latex-and-gs
description: Initialize latex and gs
runs:
  using: 'composite'
  steps:
    - name: Setup TeXLive Action
      shell: pwsh
      run: |
        choco install texlive `
          --params="'/collections:latex /scheme:basic /extraPackages:hypdoc,parskip,etoolbox,ocgx2,media9 /InstallationPath:C:/texlive/'" `
          --timeout 7200
    - name: Install ghostscript
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 120
        max_attempts: 5
        shell: pwsh
        command: choco install ghostscript --execution-timeout 7200
